[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "schnablelab"
version = "1.0.0"
keywords = ["GWAS Pipeline", "Phenotying", "UNL-HCC", "SNP Calling Pipeline", "Zooniverse"]
license = {file = "LICENSE"}
readme = "README.md"
description = "GWAS piepline & High Throughput Phenotyping related codes developed in the Schnable Lab at UNL"
requires-python = ">= 3.9"

authors = [
  {name = "Chenyong Miao"},
  {name = "Alejandro D Pages"},
  {name = "James Schnable", email = "schnable@unl.edu"},
]

maintainers = [
  {name = "Chenyong Miao"},
  {name = "James Schnable", email = "schnable@unl.edu"},
]

dependencies = [
  "numpy",
  "pandas",
  "scipy",
  "scikit-learn",
  "matplotlib",
  "seaborn",
  "tqdm",
  ""
]

[project.optional-dependencies]
deep_learning = ["torch"]

[project.urls]
Homepage = "https://example.com"
Repository = "https://github.com/me/spam.git"

[tool.setuptools]
zip-safe = false
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]