name: update mkdocs pages

on:
  pull_request:
    branches:
      - main
    types:
      - closed


jobs:
  docs:
    # Only run workflow if PR was merged (accepted, so rebuild docs)
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install code and dependencies
        run: |
          echo ${{ github.workspace }}
          pip install .
      - name: run mkdocs
        run: |
          mkdocs build --clean
          mkdocs gh-deploy --force
